filter:
    excluded_paths:
        - 'Documentation/*'
        - 'Tests/*'
        - 'Resources/*'
    paths:
        - 'Classes/*'
tools:

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: TYPO3CMS

    php_cs_fixer:
        enabled: true

    php_hhvm:
        enabled: true
        config:
            use_undeclared_constant:  false

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

build:
    tests:
        override:
            -
                command: '.Build/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-text --coverage-clover build/logs/clover.xml Tests/Unit/'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
