<?php

$EM_CONF[$_EXTKEY] = [
    'title' => 'hubiC',
    'description' => 'Cloud system synchronization with hubiC.com',
    'category' => 'fe',
    'shy' => 0,
    'dependencies' => '',
    'conflicts' => '',
    'priority' => '',
    'loadOrder' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => 0,
    'uploadfolder' => 0,
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 1,
    'lockType' => '',
    'author' => 'Philippe Court',
    'author_email' => 'contact@webstationservice.fr',
    'author_company' => 'Web Station Service',
    'CGLcompliance' => '',
    'CGLcompliance_note' => '',
    'version' => '2.0.1',
    '_md5_values_when_last_written' => '',
    'constraints' => [
        'depends' => [
            'php' => '7.0.99-7.3.999',
            'typo3' => '8.1.99-9.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
