<?php

$EM_CONF[$_EXTKEY] = array(
    'title' => 'hubiC',
    'description' => 'Cloud system synchronization with hubiC.com',
    'category' => 'fe',
    'shy' => 0,
    'dependencies' => '',
    'conflicts' => '',
    'priority' => '',
    'loadOrder' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => 0,
    'uploadfolder' => 0,
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 1,
    'lockType' => '',
    'author' => 'Philippe Court',
    'author_email' => 'contact@webstationservice.fr',
    'author_company' => 'Web Station Service',
    'CGLcompliance' => '',
    'CGLcompliance_note' => '',
    'version' => '1.0.1',
    '_md5_values_when_last_written' => '',
    'constraints' => array(
        'depends' => array(
            'php'   => '5.6-7.1.99',
            'typo3' => '7.6.0-8.9.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
