<?php
/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Filoucrackeur\Tests\Functional\Controller;

use Filoucrackeur\Hubic\Tests\Unit\AbstractFunctionalTest;
use Nimut\TestingFramework\Exception\Exception;

class HubicControllerTest extends AbstractFunctionalTest
{
// ./vendor/bin/phpunit -c ./vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml ./typo3conf/ext/hubic/Tests/Functional

    protected $testExtensionsToLoad = [
        'typo3conf/ext/hubic'
    ];

    public function setUp()
    {
        parent::setUp();

        $GLOBALS['TYPO3_CONF_VARS']['DB'] = [
            'Connections' => [
                'Default' => [
                    'charset' => 'utf8',
                    'dbname' => 'sandbox_typo3_v8',
                    'driver' => 'mysqli',
                    'host' => 'localhost',
                    'password' => '',
                    'unix_socket' => '/tmp/mysql.sock',
                    'user' => 'root',
                ],
            ],
        ];

        $this->getDatabaseConnection()->delete('pages', ['uid' => 1]);
        $this->getDatabaseConnection()->delete('tt_content', ['uid' => 1]);
        $this->getDatabaseConnection()->delete('tx_hubic_domain_model_account', ['uid' => 1]);
        $this->getDatabaseConnection()->delete('sys_template', ['uid' => 1]);

        try {
            $this->importDataSet(__DIR__ . '/../Fixtures/Database/pages.xml');
            $this->importDataSet(__DIR__ . '/../Fixtures/Database/tt_content.xml');
            $this->importDataSet(__DIR__ . '/../Fixtures/Database/tx_hubic_domain_model_account.xml');
            $this->importDataSet(__DIR__ . '/../Fixtures/Database/sys_template.xml');
        } catch (Exception $e) {
        }
    }

    /**
     * @test
     */
    public function indexControllerdisplayHello()
    {
        $this->getFrontendResponse(1);
//        var_dump($this->getFrontendResponse(1));
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
