<?php
namespace Filoucrackeur\Hubic\Controller\Backend;

use Filoucrackeur\Hubic\Service\ClientUtility;
use TYPO3\CMS\Backend\Utility\BackendUtility;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Mvc\Controller\ActionController;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;

class AccountController extends ActionController {
    /**
     * @var ClientUtility $client
     */
    protected $client;

    public function initializeAction()
    {
        parent::initializeAction(); // TODO: Change the autogenerated stub

        /* @var ClientUtility $client */
        $this->client = GeneralUtility::makeInstance(ClientUtility::class);
    }

    public function indexAction() {

        $clientAccount = $this->client->getAccount();
        $clientAccountQuota = $this->client->getAccountQuota();
        $agreement = $this->client->getAgreement();


        $this->view->assignMultiple([
            'account' => $clientAccount['result'],
            'quota' => $clientAccountQuota['result'],
            'agreement' => $agreement['result'],
            'client' => $this->client,
            'authorizationRequestUrl' => $this->client->getAuthorizationRequestUrl()
        ]);
    }

    public function infoAction() {

    }

    public function configAction() {

    }
}
